"""Train direct-512 ProNORMST under the frozen ``Pro_contract.md`` rules."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import shutil
import tempfile
import time
import warnings
from pathlib import Path
from typing import Any

import numpy as np
import torch

from datasets.pro_normst import (
    ProNORMSTData,
    ProNORMSTSlice,
    prepare_pro_normst_data,
    test_expression_identity,
)
from models.pro_normst import ProNORMST
from training.pro_normst_engine import (
    EvaluationControlCache,
    MATRIX_WEIGHT_DECAY,
    MINIMUM_LEARNING_RATE,
    OTHER_WEIGHT_DECAY,
    PEAK_LEARNING_RATE,
    PersistentIDWCache,
    WARMUP_STEPS,
    aggregate_slice_mask_records,
    build_padded_model_batch,
    canonical_json,
    canonical_sha256,
    capture_rng_state,
    diagnostic_summary,
    evaluate_mask,
    evaluate_masks,
    file_sha256,
    learning_rate_for_step,
    mean_slice_summaries,
    optimizer_for_model,
    restore_rng_state,
    seed_initialization,
    weighted_gene_smooth_l1_per_item,
)
from training.pro_normst_masks import (
    MASK_SCHEMA,
    MaskGeometry,
    ProMask,
    build_mask_geometry,
    fixed_mask_bank,
    generate_mask,
    make_mask_identity,
)


SOURCE_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PANEL = (
    SOURCE_ROOT
    / "diagnostics"
    / "dlpfc_151676_shared_panel_20260817"
    / "shared_panel_512_ensembl.txt"
)
# Bump whenever executable model/data/mask/loss/optimizer semantics change.
NUMERICAL_IMPLEMENTATION_SCHEMA = "pro-normst-numerical-v9"
HUMAN_CONTRACT_VERSION = "pro-normst-human-v9"
TEST_ARTIFACTS_DIRECTORY = "test_artifacts"
RUN_CHECKPOINT_LOCK = "run_checkpoint_lock.json"
CHECKPOINT_PREDICTION_RTOL = 2e-3
CHECKPOINT_PREDICTION_ATOL = 2e-4
OPTIMIZATION_CONTRACT = {
    "optimizer": "AdamW",
    "peak_lr": PEAK_LEARNING_RATE,
    "minimum_lr": MINIMUM_LEARNING_RATE,
    "betas": [0.9, 0.999],
    "eps": 1e-8,
    "matrix_weight_decay": MATRIX_WEIGHT_DECAY,
    "other_weight_decay": OTHER_WEIGHT_DECAY,
    "warmup_steps": WARMUP_STEPS,
    "max_epochs": 50,
    "cycles_per_epoch": 32,
    "optimizer_steps_per_epoch": 64,
    "max_steps": 3200,
    "gradient_clip": 1.0,
    "early_stopping_patience": 10,
    "early_stopping_min_delta": 1e-5,
    "validation_masks_per_slice_family": 16,
    "test_masks_per_slice_family": 16,
    "train_slice_batch_size": 4,
    "evaluation_mask_batch_size": 4,
    "batch_loss_reduction": "per-slice-gene-equal-then-slice-equal",
    "data_order_seed": 2027,
}


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--panel", type=Path, default=DEFAULT_PANEL)
    parser.add_argument("--count-file", default="filtered_feature_bc_matrix.h5")
    parser.add_argument(
        "--variant",
        choices=ProNORMST.VALID_VARIANTS,
        default="full",
        help="independently trained contracted neural method",
    )
    parser.add_argument("--seed", type=int, default=2027)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument(
        "--round-id",
        required=True,
        help="immutable identity shared by the pilot and every formal run in this round",
    )
    parser.add_argument(
        "--round-reason",
        required=True,
        help="frozen reason/hypothesis for creating this round",
    )
    parser.add_argument(
        "--device", default="cuda" if torch.cuda.is_available() else "cpu"
    )
    parser.add_argument("--resume", action="store_true")
    parser.add_argument(
        "--predict-only",
        action="store_true",
        help="load locked best checkpoint and perform the one allowed test evaluation",
    )
    parser.add_argument(
        "--checkpoint",
        type=Path,
        help="checkpoint for predict-only; defaults to output_dir/best.pt",
    )
    parser.add_argument(
        "--candidate-lock",
        type=Path,
        help="portable candidate lock generated by a passed pilot and required for formal LODO",
    )
    parser.add_argument(
        "--idw-cache-dir",
        type=Path,
        help="optional content-addressed strict-IDW cache shared by matched runs",
    )
    parser.add_argument(
        "--smoke",
        action="store_true",
        help="one full 64-step epoch engineering smoke; skips test and is not performance evidence",
    )
    return parser.parse_args(argv)


def _atomic_bytes(path: Path, writer) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle = tempfile.NamedTemporaryFile(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent, delete=False
    )
    temporary = Path(handle.name)
    handle.close()
    try:
        writer(temporary)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def _write_json(path: Path, payload: Any, *, allow_replace: bool = True) -> None:
    if path.exists() and not allow_replace:
        existing = json.loads(path.read_text(encoding="utf-8"))
        if canonical_json(existing) != canonical_json(payload):
            raise FileExistsError(f"refusing to replace incompatible artifact: {path}")
        return

    def write(temporary: Path) -> None:
        temporary.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    _atomic_bytes(path, write)


def _save_torch(path: Path, payload: dict[str, Any]) -> None:
    _atomic_bytes(path, lambda temporary: torch.save(payload, temporary))


def _device_from_argument(value: str) -> torch.device:
    device = torch.device(value)
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA was requested but is unavailable")
    if device.type not in {"cpu", "cuda"}:
        raise ValueError("ProNORMST supports only CPU or CUDA devices")
    return device


def _split_identity(data: ProNORMSTData) -> tuple[str, str]:
    protocol = str(data.split_metadata.get("protocol", ""))
    if protocol == "pair_grouped_lodo":
        fold = str(data.split_metadata.get("fold", ""))
        expected = {"train": 4, "val": 4, "test": 4}
        if not fold:
            raise ValueError("LODO manifest is missing fold identity")
    elif protocol == "pair_grouped_random_split":
        fold = f"pilot_seed{data.split_metadata.get('split_seed', 'unknown')}"
        expected = {"train": 8, "val": 2, "test": 2}
    else:
        raise ValueError(f"unsupported split protocol: {protocol}")
    actual = {role: len(items) for role, items in data.roles.items()}
    if actual != expected:
        raise ValueError(f"split role sizes {actual} do not match {expected}")
    return protocol, fold


def _validate_args(args: argparse.Namespace, protocol: str) -> None:
    round_id = str(getattr(args, "round_id", "")).strip()
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,63}", round_id):
        raise ValueError(
            "--round-id must be 1-64 characters using letters, digits, '.', '_' or '-'"
        )
    round_reason = str(getattr(args, "round_reason", "")).strip()
    if not round_reason:
        raise ValueError("--round-reason must be non-empty")
    args.round_id = round_id
    args.round_reason = round_reason
    if args.resume and args.predict_only:
        raise ValueError("--resume and --predict-only are mutually exclusive")
    if args.smoke and (args.resume or args.predict_only):
        raise ValueError("--smoke cannot be combined with resume or predict-only")
    if args.smoke:
        if args.epochs not in {1, 50}:
            raise ValueError("--smoke fixes the run to one epoch")
        args.epochs = 1
    elif args.epochs != 50:
        raise ValueError("contracted pilot/formal training uses --epochs 50; use --smoke for one epoch")
    allowed = {2027} if protocol == "pair_grouped_random_split" else {2027, 2028, 2029}
    if args.seed not in allowed:
        raise ValueError(f"initialization seed must be one of {sorted(allowed)} for {protocol}")
    if protocol == "pair_grouped_random_split" and args.variant != "full":
        raise ValueError("the contracted 8/2/2 pilot trains only the full ProNORMST candidate")
    if protocol == "pair_grouped_random_split" and args.candidate_lock is not None:
        raise ValueError("pilot runs must not consume a candidate lock")
    if protocol == "pair_grouped_lodo" and args.candidate_lock is None:
        raise ValueError("formal LODO runs require --candidate-lock from a passed pilot")


def _build_geometries(data: ProNORMSTData) -> dict[str, MaskGeometry]:
    return {
        item.slice_id: build_mask_geometry(item.neighbor_index)
        for items in data.roles.values()
        for item in items
    }


def _preload_resident_roles(
    data: ProNORMSTData,
    device: torch.device,
    roles: tuple[str, ...],
) -> dict[str, Any]:
    """Keep immutable full-slice expression/geometry tensors on one device."""
    started = time.perf_counter()
    resident_bytes = 0
    slice_ids = []
    for role in roles:
        for item in data.roles[role]:
            resident_bytes += item.preload(device)
            slice_ids.append(item.slice_id)
    return {
        "roles": list(roles),
        "slice_ids": slice_ids,
        "bytes": resident_bytes,
        "seconds": time.perf_counter() - started,
    }


def _cuda_peak_memory(device: torch.device) -> dict[str, int] | None:
    if device.type != "cuda":
        return None
    return {
        "allocated_bytes": int(torch.cuda.max_memory_allocated(device)),
        "reserved_bytes": int(torch.cuda.max_memory_reserved(device)),
    }


def _persistent_idw_cache_status(
    cache: PersistentIDWCache | None,
) -> dict[str, Any] | None:
    if cache is None:
        return None
    return {
        "root": str(cache.root),
        "hits": cache.hits,
        "misses": cache.misses,
        "writes": cache.writes,
    }


def _build_fixed_banks(
    data: ProNORMSTData,
    geometries: dict[str, MaskGeometry],
    protocol: str,
    fold: str,
) -> dict[str, dict[str, dict[str, tuple[ProMask, ...]]]]:
    banks: dict[str, dict[str, dict[str, tuple[ProMask, ...]]]] = {"val": {}, "test": {}}
    for role in ("val", "test"):
        for item in data.roles[role]:
            banks[role][item.slice_id] = {
                family: fixed_mask_bank(
                    geometries[item.slice_id],
                    protocol=protocol,
                    fold=fold,
                    role=role,
                    slice_id=item.slice_id,
                    family=family,
                )
                for family in ("ordinary", "gap")
            }
    return banks


def _compact_mask_manifest(mask: ProMask) -> dict[str, Any]:
    unique_depth, depth_count = np.unique(mask.depth, return_counts=True)
    unique_provenance, provenance_count = np.unique(mask.provenance, return_counts=True)
    return {
        "identity": mask.identity,
        "n_target": mask.n_target,
        "n_query": int(mask.query_index.size),
        "realized_fraction": mask.realized_fraction,
        "provenance_counts": {
            str(key): int(value) for key, value in zip(unique_provenance, provenance_count)
        },
        "depth_counts": {str(int(key)): int(value) for key, value in zip(unique_depth, depth_count)},
        "hole_sizes": [len(hole.nodes) for hole in mask.holes],
        "hole_radii": [hole.radius for hole in mask.holes],
        "query_components": int(np.unique(mask.query_component).size),
        "substream_seeds": mask.substream_seeds,
    }


def _write_npz_once(path: Path, arrays: dict[str, np.ndarray]) -> None:
    """Atomically create an NPZ, accepting only identical retry content."""

    if path.exists():
        with np.load(path, allow_pickle=False) as saved:
            if set(saved.files) != set(arrays) or any(
                not np.array_equal(saved[name], arrays[name]) for name in arrays
            ):
                raise FileExistsError(f"refusing to replace incompatible artifact: {path}")
        return

    def write(temporary: Path) -> None:
        with temporary.open("wb") as handle:
            np.savez_compressed(handle, **arrays)

    _atomic_bytes(path, write)


def _save_training_mask_epoch(
    output_dir: Path,
    epoch: int,
    masks: list[ProMask],
) -> dict[str, str]:
    """Save every training mask's query/depth/component metadata compactly."""

    if not masks:
        raise ValueError("cannot save an empty training mask epoch")
    provenance_labels = sorted(
        {str(value) for mask in masks for value in np.unique(mask.provenance)}
    )
    provenance_code = {label: index for index, label in enumerate(provenance_labels)}
    offsets = np.zeros(len(masks) + 1, dtype=np.int64)
    for index, mask in enumerate(masks):
        offsets[index + 1] = offsets[index] + mask.query_index.size
    arrays = {
        "offsets": offsets,
        "query_index": np.concatenate([mask.query_index for mask in masks]).astype("<i8"),
        "depth": np.concatenate([mask.depth for mask in masks]).astype("<i4"),
        "query_component": np.concatenate(
            [mask.query_component for mask in masks]
        ).astype("<i4"),
        "query_component_size": np.concatenate(
            [mask.query_component_size for mask in masks]
        ).astype("<i4"),
        "full_degree": np.concatenate([mask.full_degree for mask in masks]).astype("<i2"),
        "provenance_code": np.concatenate(
            [
                np.asarray([provenance_code[str(value)] for value in mask.provenance])
                for mask in masks
            ]
        ).astype(np.uint8),
    }
    artifact_dir = output_dir / "training_masks"
    npz_path = artifact_dir / f"epoch_{epoch:03d}.npz"
    _write_npz_once(npz_path, arrays)
    summaries = []
    for index, mask in enumerate(masks):
        summary = _compact_mask_manifest(mask)
        summary["array_offset"] = [int(offsets[index]), int(offsets[index + 1])]
        summaries.append(summary)
    manifest_path = artifact_dir / f"epoch_{epoch:03d}.json"
    _write_json(
        manifest_path,
        {
            "schema": "pro-normst-training-mask-epoch-v1",
            "epoch": epoch,
            "npz": npz_path.name,
            "npz_sha256": file_sha256(npz_path),
            "provenance_labels": provenance_labels,
            "masks": summaries,
        },
        allow_replace=False,
    )
    return {
        "manifest_sha256": file_sha256(manifest_path),
        "npz_sha256": file_sha256(npz_path),
    }


def _save_run_artifacts(
    output_dir: Path,
    args: argparse.Namespace,
    data: ProNORMSTData,
    model: ProNORMST,
    parameter_groups: dict[str, list[str]],
    protocol: str,
    fold: str,
    contract_manifest: dict[str, Any],
    contract_hash: str,
    banks: dict[str, dict[str, dict[str, tuple[ProMask, ...]]]],
) -> None:
    config = {
        "schema": "pro-normst-run-config-v3",
        "model": "pro-normst",
        "human_contract_version": HUMAN_CONTRACT_VERSION,
        "round_identity": args.round_id,
        "round_reason": args.round_reason,
        "variant": args.variant,
        "manifest": str(args.manifest.resolve()),
        "panel": str(args.panel.resolve()),
        "count_file": args.count_file,
        "output_dir": str(output_dir),
        "initialization_seed": args.seed,
        "data_order_seed": 2027,
        "protocol": protocol,
        "fold": fold,
        "epochs": args.epochs,
        "smoke": bool(args.smoke),
        "evidence_tier": "real-data-smoke" if args.smoke else ("pilot" if protocol == "pair_grouped_random_split" else "formal-lodo"),
        "contract_hash": contract_hash,
        "candidate_lock": (
            str(args.candidate_lock.resolve()) if args.candidate_lock is not None else None
        ),
        "idw_cache_dir": (
            str(getattr(args, "idw_cache_dir").resolve())
            if getattr(args, "idw_cache_dir", None) is not None
            else None
        ),
    }
    _write_json(output_dir / "config.json", config, allow_replace=False)
    _write_json(output_dir / "contract_manifest.json", contract_manifest, allow_replace=False)
    _write_json(
        output_dir / "round_freeze.json",
        {
            "schema": "pro-normst-round-freeze-v1",
            "human_contract_version": HUMAN_CONTRACT_VERSION,
            "round_identity": args.round_id,
            "round_reason": args.round_reason,
            "numerical_implementation_schema": NUMERICAL_IMPLEMENTATION_SCHEMA,
            "numerical_contract_sha256": contract_hash,
            "config": config,
            "contract_manifest": contract_manifest,
        },
        allow_replace=False,
    )
    _write_json(output_dir / "optimizer_parameter_groups.json", parameter_groups, allow_replace=False)
    _write_json(output_dir / "split_metadata.json", data.split_metadata, allow_replace=False)
    _write_json(
        output_dir / "split_manifest.snapshot.json",
        json.loads(args.manifest.resolve().read_text(encoding="utf-8")),
        allow_replace=False,
    )
    _write_json(output_dir / "environment.json", {
        "python": __import__("sys").version,
        "torch": str(torch.__version__),
        "numpy": str(np.__version__),
        "cuda": torch.version.cuda,
        "device_request": args.device,
    }, allow_replace=False)
    (output_dir / "genes.txt").write_text("\n".join(data.preprocessing.gene_ids) + "\n", encoding="utf-8")
    np.savez(
        output_dir / "preprocessing.npz",
        gene_scale=data.preprocessing.gene_scale,
        detection_rate=data.preprocessing.detection_rate,
        positive_weight=data.preprocessing.positive_weight,
        gene_mean_z=data.preprocessing.gene_mean_z,
    )
    for role, role_banks in banks.items():
        for slice_id, family_banks in role_banks.items():
            for family, masks in family_banks.items():
                for index, mask in enumerate(masks):
                    _write_json(
                        output_dir / "mask_banks" / role / slice_id / family / f"mask_{index:02d}.json",
                        mask.manifest(),
                        allow_replace=False,
                    )


def _validate_existing_run(
    output_dir: Path,
    args: argparse.Namespace,
    data: ProNORMSTData,
    contract_manifest: dict[str, Any],
    contract_hash: str,
) -> None:
    config = json.loads((output_dir / "config.json").read_text(encoding="utf-8"))
    if config.get("contract_hash") != contract_hash:
        raise ValueError("run directory contract is incompatible with current arguments/data")
    requested_round = getattr(args, "round_id", None)
    requested_reason = getattr(args, "round_reason", None)
    if requested_round is not None and config.get("round_identity") != requested_round:
        raise ValueError("run directory round identity is incompatible")
    if requested_reason is not None and config.get("round_reason") != requested_reason:
        raise ValueError("run directory round reason is incompatible")
    freeze = json.loads((output_dir / "round_freeze.json").read_text(encoding="utf-8"))
    if (
        freeze.get("human_contract_version") != HUMAN_CONTRACT_VERSION
        or freeze.get("round_identity") != config.get("round_identity")
        or freeze.get("round_reason") != config.get("round_reason")
        or freeze.get("numerical_contract_sha256") != contract_hash
    ):
        raise ValueError("saved round freeze is incompatible")
    saved_contract = json.loads(
        (output_dir / "contract_manifest.json").read_text(encoding="utf-8")
    )
    if (
        canonical_json(freeze.get("config")) != canonical_json(config)
        or canonical_json(freeze.get("contract_manifest"))
        != canonical_json(saved_contract)
    ):
        raise ValueError("saved round freeze content changed")
    saved_numerical = _numerical_contract(saved_contract)
    current_numerical = _numerical_contract(contract_manifest)
    if canonical_json(saved_numerical) != canonical_json(current_numerical):
        raise ValueError("saved numerical compatibility contract has changed")
    if _audit_provenance(saved_contract) != _audit_provenance(contract_manifest):
        warnings.warn(
            "audit provenance changed while the numerical compatibility contract remained stable",
            RuntimeWarning,
            stacklevel=2,
        )
    saved_genes = tuple(
        line.strip()
        for line in (output_dir / "genes.txt").read_text(encoding="utf-8").splitlines()
        if line.strip()
    )
    if saved_genes != data.preprocessing.gene_ids:
        raise ValueError("saved gene order is incompatible")
    with np.load(output_dir / "preprocessing.npz") as saved:
        for name in ("gene_scale", "detection_rate", "positive_weight", "gene_mean_z"):
            if not np.array_equal(saved[name], getattr(data.preprocessing, name)):
                raise ValueError(f"saved preprocessing artifact changed: {name}")
    current_split = json.loads(args.manifest.resolve().read_text(encoding="utf-8"))
    saved_split = json.loads(
        (output_dir / "split_manifest.snapshot.json").read_text(encoding="utf-8")
    )
    if canonical_json(current_split) != canonical_json(saved_split):
        raise ValueError("saved split manifest is incompatible")


def _contract_manifest(
    args: argparse.Namespace,
    data: ProNORMSTData,
    model: ProNORMST,
    protocol: str,
    fold: str,
    geometries: dict[str, MaskGeometry],
    banks: dict[str, dict[str, dict[str, tuple[ProMask, ...]]]],
) -> dict[str, Any]:
    def array_hash(value: np.ndarray) -> str:
        array = np.ascontiguousarray(value)
        digest = hashlib.sha256()
        digest.update(str(array.dtype).encode("ascii"))
        digest.update(canonical_json(list(array.shape)).encode("ascii"))
        digest.update(array.tobytes(order="C"))
        return digest.hexdigest()

    slice_contract = {}
    for role, slices in data.roles.items():
        for item in slices:
            item_contract = {
                "role": role,
                "barcodes_sha256": canonical_sha256(list(item.barcodes)),
                "full_xy_sha256": array_hash(item.full_xy.astype("<f4")),
                "neighbor_index_sha256": array_hash(
                    geometries[item.slice_id].neighbor_index.astype("<i8")
                ),
                "native_scale": item.native_scale,
                "source_barcodes_sha256": item.source_barcodes_sha256,
                "source_gex_gene_ids_sha256": item.source_gex_gene_ids_sha256,
                "source_panel_indices_sha256": item.source_panel_indices_sha256,
            }
            if role == "test":
                item_contract["expression_access"] = (
                    "loaded_read_only_excluded_from_fit_and_model_selection"
                )
            else:
                item_contract["expression_access"] = "materialized_before_training"
            item_contract["expression_x_sha256"] = array_hash(
                item.expression_x.astype("<f4")
            )
            slice_contract[item.slice_id] = item_contract
    fixed_bank_contract = {
        role: {
            slice_id: {
                family: [array_hash(mask.query_index.astype("<i8")) for mask in masks]
                for family, masks in family_banks.items()
            }
            for slice_id, family_banks in role_banks.items()
        }
        for role, role_banks in banks.items()
    }
    return {
        "schema": "pro-normst-training-contract-v4",
        "human_contract_version": HUMAN_CONTRACT_VERSION,
        "round": {
            "identity": args.round_id,
            "reason": args.round_reason,
        },
        "numerical_implementation_schema": NUMERICAL_IMPLEMENTATION_SCHEMA,
        "model": model.contract_manifest(),
        "preprocessing": data.preprocessing.manifest(),
        "mask_schema": MASK_SCHEMA,
        "fixed_mask_banks": fixed_bank_contract,
        "slice_data_and_geometry": slice_contract,
        "loss_schema": "gene-equal-target-weighted-smooth-l1-beta1-v1",
        "metric_schema": "raw-x-model-idw-stratified-v1",
        "optimization": OPTIMIZATION_CONTRACT,
        "split": {
            "protocol": protocol,
            "fold": fold,
            "role_sizes": {role: len(items) for role, items in data.roles.items()},
        },
        "run": {
            "variant": args.variant,
            "initialization_seed": args.seed,
            "smoke": bool(args.smoke),
            "epochs": args.epochs,
            "precision": "cuda-fp16-amp" if str(args.device).startswith("cuda") else "cpu-fp32",
            "candidate_lock_sha256": (
                file_sha256(args.candidate_lock.resolve())
                if args.candidate_lock is not None
                else None
            ),
        },
        "runtime": {"torch": str(torch.__version__), "numpy": str(np.__version__)},
    }


def _numerical_contract(contract_manifest: dict[str, Any]) -> dict[str, Any]:
    """Return only fields that can change training or locked predictions."""

    run = dict(contract_manifest["run"])
    run.pop("candidate_lock_sha256", None)
    return {
        "schema": "pro-normst-numerical-compatibility-v1",
        "numerical_implementation_schema": contract_manifest[
            "numerical_implementation_schema"
        ],
        "model": contract_manifest["model"],
        "preprocessing": contract_manifest["preprocessing"],
        "mask_schema": contract_manifest["mask_schema"],
        "fixed_mask_banks": contract_manifest["fixed_mask_banks"],
        "slice_data_and_geometry": contract_manifest["slice_data_and_geometry"],
        "loss_schema": contract_manifest["loss_schema"],
        "metric_schema": contract_manifest["metric_schema"],
        "optimization": contract_manifest["optimization"],
        "split": contract_manifest["split"],
        "run": run,
    }


def _numerical_contract_hash(contract_manifest: dict[str, Any]) -> str:
    return canonical_sha256(_numerical_contract(contract_manifest))


def _audit_provenance(contract_manifest: dict[str, Any]) -> dict[str, Any]:
    """Return recorded provenance that must not decide resume compatibility."""

    return {
        "human_contract_version": contract_manifest.get("human_contract_version"),
        "round": contract_manifest.get("round"),
        "runtime": contract_manifest.get("runtime"),
        "candidate_lock_sha256": contract_manifest.get("run", {}).get(
            "candidate_lock_sha256"
        ),
    }


def _comparison_contract(contract_manifest: dict[str, Any]) -> dict[str, Any]:
    """Contract subset that must remain identical from pilot to formal runs."""

    model = dict(contract_manifest["model"])
    model.pop("variant", None)
    model.pop("max_rounds", None)
    preprocessing = contract_manifest["preprocessing"]
    return {
        "schema": "pro-normst-comparison-contract-v1",
        "human_contract_version": contract_manifest.get("human_contract_version"),
        "round_identity": contract_manifest.get("round", {}).get("identity"),
        "numerical_implementation_schema": contract_manifest[
            "numerical_implementation_schema"
        ],
        "model_common": model,
        "panel_size": preprocessing["panel_size"],
        "panel_ordered_sha256": preprocessing["panel_ordered_sha256"],
        "transform": preprocessing["transform"],
        "scale": preprocessing["scale"],
        "mask_schema": contract_manifest["mask_schema"],
        "loss_schema": contract_manifest["loss_schema"],
        "metric_schema": contract_manifest["metric_schema"],
        "optimization": contract_manifest["optimization"],
        "precision": contract_manifest["run"]["precision"],
    }


def _compact_bptt_gate(gate: dict[str, Any]) -> dict[str, Any]:
    required_rounds = gate.get("required_rounds")
    witness = None
    if isinstance(required_rounds, int):
        records = gate.get("records", [])
        if not isinstance(records, list):
            records = []
        for record in records:
            if not isinstance(record, dict):
                continue
            values = record.get("round_gradient_norm")
            if not isinstance(values, list) or len(values) != required_rounds:
                continue
            if all(
                isinstance(value, (int, float))
                and not isinstance(value, bool)
                and math.isfinite(float(value))
                and float(value) > 0
                for value in values
            ):
                witness = {
                    "epoch": record.get("epoch"),
                    "global_step": record.get("global_step"),
                    "round_gradient_norm": [float(value) for value in values],
                }
                break
    return {
        "passed": gate.get("passed"),
        "applicable": gate.get("applicable"),
        "required_rounds": required_rounds,
        "witness": witness,
    }


def _validate_candidate_gates(gates: Any) -> None:
    if not isinstance(gates, dict):
        raise ValueError("candidate lock gates are missing")
    gradient = gates.get("gradient", {})
    if not (
        gradient.get("passed") is True
        and gradient.get("missing_nonzero_gradient") == []
    ):
        raise ValueError("candidate lock gradient gate is invalid")

    bptt = gates.get("final_loss_bptt", {})
    witness = bptt.get("witness", {})
    values = witness.get("round_gradient_norm") if isinstance(witness, dict) else None
    if not (
        bptt.get("passed") is True
        and bptt.get("applicable") is True
        and bptt.get("required_rounds") == 4
        and isinstance(values, list)
        and len(values) == 4
        and all(
            isinstance(value, (int, float))
            and not isinstance(value, bool)
            and math.isfinite(float(value))
            and float(value) > 0
            for value in values
        )
    ):
        raise ValueError("candidate lock final-loss BPTT gate is invalid")

    health = gates.get("pilot_health", {})
    if health.get("passed") is not True:
        raise ValueError("candidate lock pilot health gate is invalid")
    families = health.get("families", {})
    if not isinstance(families, dict) or set(families) != {"ordinary", "gap"}:
        raise ValueError("candidate lock pilot health families are invalid")
    for family in ("ordinary", "gap"):
        item = families[family]
        if not isinstance(item, dict):
            raise ValueError(f"candidate lock {family} pilot metrics are invalid")
        values = (
            item.get("model_smooth_l1"),
            item.get("idw_smooth_l1"),
            item.get("variance_ratio_median"),
        )
        if not all(
            isinstance(value, (int, float))
            and not isinstance(value, bool)
            and math.isfinite(float(value))
            for value in values
        ):
            raise ValueError(f"candidate lock {family} pilot metrics are invalid")
        model_smooth, idw_smooth, variance = (float(value) for value in values)
        if not (
            item.get("passed") is True
            and model_smooth >= 0
            and idw_smooth >= 0
            and model_smooth <= 1.2 * idw_smooth
            and 1e-3 <= variance <= 10.0
        ):
            raise ValueError(f"candidate lock {family} pilot threshold failed")


def _is_sha256(value: Any) -> bool:
    return (
        isinstance(value, str)
        and len(value) == 64
        and all(character in "0123456789abcdef" for character in value)
    )


def _write_candidate_lock(
    output_dir: Path,
    contract_manifest: dict[str, Any],
) -> Path:
    config = json.loads((output_dir / "config.json").read_text(encoding="utf-8"))
    gradient_gate = json.loads(
        (output_dir / "gradient_gate.json").read_text(encoding="utf-8")
    )
    bptt_gate = json.loads(
        (output_dir / "final_loss_bptt_gate.json").read_text(encoding="utf-8")
    )
    pilot_gate = json.loads(
        (output_dir / "pilot_gate.json").read_text(encoding="utf-8")
    )
    valid = (
        config.get("protocol") == "pair_grouped_random_split"
        and config.get("fold") == "pilot_seed2027"
        and config.get("variant") == "full"
        and config.get("initialization_seed") == 2027
        and not bool(config.get("smoke"))
        and gradient_gate.get("passed") is True
        and bptt_gate.get("passed") is True
        and pilot_gate.get("passed") is True
    )
    if not valid:
        raise RuntimeError("pilot artifacts do not satisfy the candidate-lock contract")
    gates = {
        "gradient": {
            "passed": gradient_gate.get("passed"),
            "missing_nonzero_gradient": gradient_gate.get(
                "missing_nonzero_gradient"
            ),
        },
        "final_loss_bptt": _compact_bptt_gate(bptt_gate),
        "pilot_health": pilot_gate,
    }
    try:
        _validate_candidate_gates(gates)
    except ValueError as error:
        raise RuntimeError(
            "pilot artifacts do not satisfy the candidate-lock contract"
        ) from error
    signature = _comparison_contract(contract_manifest)
    checkpoint_path = output_dir / "best.pt"
    if not checkpoint_path.is_file():
        raise FileNotFoundError(
            f"pilot run is missing required checkpoint: {checkpoint_path.name}"
        )
    payload = {
        "schema": "pro-normst-candidate-lock-v4",
        "status": "locked",
        "human_contract_version": HUMAN_CONTRACT_VERSION,
        "round_identity": config.get("round_identity"),
        "candidate_signature": signature,
        "candidate_signature_sha256": canonical_sha256(signature),
        "pilot_identity": {
            "protocol": config.get("protocol"),
            "fold": config.get("fold"),
            "variant": config.get("variant"),
            "initialization_seed": config.get("initialization_seed"),
            "smoke": bool(config.get("smoke")),
        },
        "gates": gates,
        "checkpoint_sha256": file_sha256(checkpoint_path),
    }
    path = output_dir / "candidate_lock.json"
    _write_json(path, payload, allow_replace=False)
    return path


def _validate_candidate_lock(
    path: Path,
    contract_manifest: dict[str, Any],
) -> dict[str, Any]:
    lock_path = path.resolve()
    payload = json.loads(lock_path.read_text(encoding="utf-8"))
    if payload.get("schema") != "pro-normst-candidate-lock-v4":
        raise ValueError("candidate lock schema is incompatible")
    if payload.get("status") != "locked":
        raise ValueError("candidate lock is not locked")
    if payload.get("human_contract_version") != HUMAN_CONTRACT_VERSION:
        raise ValueError("candidate lock human contract version is incompatible")
    expected_round = contract_manifest.get("round", {}).get("identity")
    if payload.get("round_identity") != expected_round:
        raise ValueError("candidate lock round identity is incompatible")
    signature = payload.get("candidate_signature")
    if payload.get("candidate_signature_sha256") != canonical_sha256(signature):
        raise ValueError("candidate lock signature hash is invalid")
    if canonical_json(signature) != canonical_json(_comparison_contract(contract_manifest)):
        raise ValueError("candidate lock signature does not match this run")
    identity = payload.get("pilot_identity", {})
    expected_identity = {
        "protocol": "pair_grouped_random_split",
        "fold": "pilot_seed2027",
        "variant": "full",
        "initialization_seed": 2027,
        "smoke": False,
    }
    if identity != expected_identity:
        raise ValueError("candidate lock pilot identity is invalid")
    if not _is_sha256(payload.get("checkpoint_sha256")):
        raise ValueError("candidate lock checkpoint hash is invalid")
    _validate_candidate_gates(payload.get("gates"))
    return payload


def _write_run_checkpoint_lock(
    output_dir: Path,
    checkpoint_path: Path,
    checkpoint: dict[str, Any],
    contract_hash: str,
) -> Path:
    """Lock a formal run's validation-selected best checkpoint before test."""

    config = json.loads((output_dir / "config.json").read_text(encoding="utf-8"))
    if config.get("protocol") != "pair_grouped_lodo":
        raise ValueError("run checkpoint locks are only valid for formal LODO runs")
    payload = {
        "schema": "pro-normst-run-checkpoint-lock-v1",
        "status": "locked",
        "human_contract_version": HUMAN_CONTRACT_VERSION,
        "round_identity": config.get("round_identity"),
        "fold": config.get("fold"),
        "initialization_seed": config.get("initialization_seed"),
        "variant": config.get("variant"),
        "contract_hash": contract_hash,
        "checkpoint": "best.pt",
        "checkpoint_sha256": file_sha256(checkpoint_path),
        "best_epoch": int(checkpoint["best_epoch"]),
        "best_validation": float(checkpoint["best_value"]),
    }
    path = output_dir / RUN_CHECKPOINT_LOCK
    _write_json(path, payload, allow_replace=False)
    return path


def _validate_run_checkpoint_lock(
    path: Path,
    checkpoint_path: Path,
    contract_hash: str,
) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    valid = (
        payload.get("schema") == "pro-normst-run-checkpoint-lock-v1"
        and payload.get("status") == "locked"
        and payload.get("human_contract_version") == HUMAN_CONTRACT_VERSION
        and payload.get("contract_hash") == contract_hash
        and payload.get("checkpoint") == "best.pt"
        and payload.get("checkpoint_sha256") == file_sha256(checkpoint_path)
        and isinstance(payload.get("best_epoch"), int)
        and isinstance(payload.get("best_validation"), (int, float))
        and math.isfinite(float(payload.get("best_validation", math.nan)))
    )
    if not valid:
        raise ValueError("formal run checkpoint lock is invalid")
    return payload


def _minimal_metric_record(record: dict[str, Any]) -> dict[str, Any]:
    mask = record["mask"]
    record["mask"] = {
        "identity": mask["identity"],
        "n_target": mask["n_target"],
        "n_query": mask["n_query"],
        "realized_fraction": mask["realized_fraction"],
        "provenance_counts": mask["provenance_counts"],
    }
    return record


def _evaluate_role(
    model: ProNORMST,
    data: ProNORMSTData,
    role: str,
    banks: dict[str, dict[str, dict[str, tuple[ProMask, ...]]]],
    device: torch.device,
    *,
    use_amp: bool,
    output_dir: Path | None = None,
    prediction_label: str | None = None,
    round_limit: int | None = None,
    detail: str = "full",
    control_cache: EvaluationControlCache | None = None,
    persistent_idw_cache: PersistentIDWCache | None = None,
) -> dict[str, Any]:
    if detail not in {"full", "summary"}:
        raise ValueError("evaluation detail must be 'full' or 'summary'")
    model.eval()
    positive_weight = torch.as_tensor(
        data.preprocessing.positive_weight,
        dtype=torch.float32,
        device=device,
    )
    family_output: dict[str, Any] = {}
    for family in ("ordinary", "gap"):
        slice_summaries = []
        slice_output: dict[str, Any] = {}
        for item in data.roles[role]:
            records = []
            mask_bank = banks[role][item.slice_id][family]
            evaluation_batch_size = OPTIMIZATION_CONTRACT[
                "evaluation_mask_batch_size"
            ]
            for batch_start in range(0, len(mask_bank), evaluation_batch_size):
                mask_batch = mask_bank[
                    batch_start : batch_start + evaluation_batch_size
                ]
                save_prediction = output_dir is not None and prediction_label is not None
                batch_records = (
                    [
                        evaluate_mask(
                            model,
                            item,
                            mask_batch[0],
                            data.preprocessing.gene_scale,
                            positive_weight,
                            data.preprocessing.detection_rate,
                            device,
                            use_amp=use_amp,
                            round_limit=round_limit,
                            return_prediction=save_prediction,
                            control_cache=control_cache,
                            persistent_idw_cache=persistent_idw_cache,
                        )
                    ]
                    if len(mask_batch) == 1
                    else evaluate_masks(
                        model,
                        item,
                        mask_batch,
                        data.preprocessing.gene_scale,
                        positive_weight,
                        data.preprocessing.detection_rate,
                        device,
                        use_amp=use_amp,
                        round_limit=round_limit,
                        return_prediction=save_prediction,
                        control_cache=control_cache,
                        persistent_idw_cache=persistent_idw_cache,
                    )
                )
                for batch_offset, (mask, record) in enumerate(
                    zip(mask_batch, batch_records, strict=True)
                ):
                    mask_offset = batch_start + batch_offset
                    if save_prediction:
                        prediction_path = (
                            output_dir
                            / "predictions"
                            / prediction_label
                            / item.slice_id
                            / family
                            / f"mask_{mask_offset:02d}.npz"
                        )
                        if prediction_path.exists():
                            raise FileExistsError(
                                f"refusing to overwrite prediction: {prediction_path}"
                            )
                        prediction_path.parent.mkdir(parents=True, exist_ok=True)
                        np.savez_compressed(
                            prediction_path,
                            prediction_z=record.pop("prediction_z"),
                            prediction_x=record.pop("prediction_x"),
                            target_x=record.pop("target_x"),
                            idw_x=record.pop("idw_x"),
                            query_index=mask.query_index,
                            visible_index=mask.visible_index,
                            provenance=mask.provenance,
                            depth=mask.depth,
                        )
                    records.append(_minimal_metric_record(record))
            summary = aggregate_slice_mask_records(records)
            slice_summaries.append(summary)
            if detail == "full":
                slice_output[item.slice_id] = {"summary": summary, "masks": records}
        family_summary = mean_slice_summaries(slice_summaries)
        family_output[family] = {"summary": family_summary}
        if detail == "full":
            family_output[family]["slices"] = slice_output
    criterion = float(
        0.5
        * (
            family_output["ordinary"]["summary"]["weighted_z_smooth_l1"]
            + family_output["gap"]["summary"]["weighted_z_smooth_l1"]
        )
    )
    return {
        "role": role,
        "round_limit": round_limit,
        "criterion_weighted_z_smooth_l1": criterion,
        "families": family_output,
    }


def _checkpoint_payload(
    *,
    model: ProNORMST,
    optimizer: torch.optim.Optimizer,
    scaler: torch.amp.GradScaler,
    data_order_generator: torch.Generator,
    contract_hash: str,
    epoch: int,
    global_step: int,
    best_value: float,
    best_epoch: int,
    bad_epochs: int,
    history: list[dict[str, Any]],
    gradient_cache: dict[str, float],
    gradient_seen: dict[str, bool],
) -> dict[str, Any]:
    return {
        "schema": "pro-normst-checkpoint-v1",
        "contract_hash": contract_hash,
        "model": model.state_dict(),
        "optimizer": optimizer.state_dict(),
        "scheduler": {
            "schema": "linear-warmup-cosine-v1",
            "completed_steps": global_step,
            "next_lr": learning_rate_for_step(global_step + 1)
            if global_step < OPTIMIZATION_CONTRACT["max_steps"]
            else OPTIMIZATION_CONTRACT["minimum_lr"],
        },
        "scaler": scaler.state_dict(),
        "rng": capture_rng_state(data_order_generator),
        "epoch": epoch,
        "global_step": global_step,
        "cycle": 0,
        "best_value": best_value,
        "best_epoch": best_epoch,
        "bad_epochs": bad_epochs,
        "history": history,
        "gradient_cache": gradient_cache,
        "gradient_seen": gradient_seen,
    }


def _load_checkpoint(
    path: Path,
    model: ProNORMST,
    contract_hash: str,
    device: torch.device,
    optimizer: torch.optim.Optimizer | None = None,
    scaler: torch.amp.GradScaler | None = None,
    data_order_generator: torch.Generator | None = None,
) -> dict[str, Any]:
    checkpoint = torch.load(path, map_location=device, weights_only=False)
    if checkpoint.get("schema") != "pro-normst-checkpoint-v1":
        raise ValueError("checkpoint schema is not ProNORMST")
    if checkpoint.get("contract_hash") != contract_hash:
        raise ValueError("checkpoint contract hash is incompatible with this run")
    model.load_state_dict(checkpoint["model"], strict=True)
    if optimizer is not None:
        optimizer.load_state_dict(checkpoint["optimizer"])
    if scaler is not None:
        scaler.load_state_dict(checkpoint["scaler"])
    if data_order_generator is not None:
        restore_rng_state(checkpoint["rng"], data_order_generator)
    return checkpoint


def _state_tree_equal(left: Any, right: Any) -> bool:
    if isinstance(left, torch.Tensor) and isinstance(right, torch.Tensor):
        return left.shape == right.shape and bool(torch.equal(left.cpu(), right.cpu()))
    if isinstance(left, dict) and isinstance(right, dict):
        return left.keys() == right.keys() and all(
            _state_tree_equal(left[key], right[key]) for key in left
        )
    if isinstance(left, (list, tuple)) and isinstance(right, type(left)):
        return len(left) == len(right) and all(
            _state_tree_equal(a, b) for a, b in zip(left, right)
        )
    return left == right


def _verify_smoke_checkpoint(
    *,
    model: ProNORMST,
    optimizer: torch.optim.Optimizer,
    scaler: torch.amp.GradScaler,
    data_order_generator: torch.Generator,
    data: ProNORMSTData,
    banks: dict[str, dict[str, dict[str, tuple[ProMask, ...]]]],
    output_dir: Path,
    device: torch.device,
    use_amp: bool,
    contract_hash: str,
) -> dict[str, Any]:
    """Exercise full resume state and locked-checkpoint prediction after smoke."""

    restored = ProNORMST(
        torch.as_tensor(data.preprocessing.gene_mean_z), variant=model.variant
    ).to(device)
    restored_optimizer, _ = optimizer_for_model(restored)
    restored_scaler = torch.amp.GradScaler(device.type, enabled=use_amp)
    restored_generator = torch.Generator(device="cpu").manual_seed(0)
    checkpoint = _load_checkpoint(
        output_dir / "last.pt",
        restored,
        contract_hash,
        device,
        optimizer=restored_optimizer,
        scaler=restored_scaler,
        data_order_generator=restored_generator,
    )
    first_val = data.roles["val"][0]
    first_mask = banks["val"][first_val.slice_id]["gap"][0]
    verification_control_cache: EvaluationControlCache = {}
    current = evaluate_mask(
        model,
        first_val,
        first_mask,
        data.preprocessing.gene_scale,
        data.preprocessing.positive_weight,
        data.preprocessing.detection_rate,
        device,
        use_amp=use_amp,
        return_prediction=True,
        control_cache=verification_control_cache,
    )["prediction_z"]
    reloaded = evaluate_mask(
        restored,
        first_val,
        first_mask,
        data.preprocessing.gene_scale,
        data.preprocessing.positive_weight,
        data.preprocessing.detection_rate,
        device,
        use_amp=use_amp,
        return_prediction=True,
        control_cache=verification_control_cache,
    )["prediction_z"]
    absolute_error = np.abs(current.astype(np.float64) - reloaded.astype(np.float64))
    relative_error = absolute_error / np.maximum(
        np.abs(reloaded.astype(np.float64)), CHECKPOINT_PREDICTION_ATOL
    )
    checks = {
        "model_state_round_trip": _state_tree_equal(
            model.state_dict(), restored.state_dict()
        ),
        "optimizer_state_round_trip": _state_tree_equal(
            optimizer.state_dict(), restored_optimizer.state_dict()
        ),
        "scaler_state_round_trip": _state_tree_equal(
            scaler.state_dict(), restored_scaler.state_dict()
        ),
        "data_order_rng_round_trip": bool(
            torch.equal(
                data_order_generator.get_state(), restored_generator.get_state()
            )
        ),
        "resume_epoch_and_step": (
            int(checkpoint["epoch"]) == 1
            and int(checkpoint["global_step"])
            == OPTIMIZATION_CONTRACT["optimizer_steps_per_epoch"]
        ),
        "locked_checkpoint_prediction": bool(
            np.allclose(
                current,
                reloaded,
                rtol=CHECKPOINT_PREDICTION_RTOL,
                atol=CHECKPOINT_PREDICTION_ATOL,
            )
        ),
        "test_expression_loaded_by_scanpy": all(
            isinstance(item.expression_x, np.ndarray)
            and isinstance(item.expression_z, np.ndarray)
            for item in data.roles["test"]
        ),
    }
    result = {
        "schema": "pro-normst-smoke-verification-v1",
        "passed": all(checks.values()),
        "checks": checks,
        "prediction_tolerance": {
            "rtol": CHECKPOINT_PREDICTION_RTOL,
            "atol": CHECKPOINT_PREDICTION_ATOL,
            "max_abs_error": float(absolute_error.max(initial=0.0)),
            "max_relative_error": float(relative_error.max(initial=0.0)),
        },
        "checkpoint_sha256": file_sha256(output_dir / "last.pt"),
    }
    _write_json(output_dir / "smoke_verification.json", result, allow_replace=False)
    if not result["passed"]:
        raise RuntimeError(f"smoke checkpoint verification failed: {checks}")
    return result


def _train_one_epoch(
    *,
    model: ProNORMST,
    data: ProNORMSTData,
    geometries: dict[str, MaskGeometry],
    optimizer: torch.optim.Optimizer,
    scaler: torch.amp.GradScaler,
    data_order_generator: torch.Generator,
    device: torch.device,
    use_amp: bool,
    protocol: str,
    fold: str,
    epoch: int,
    global_step: int,
    cycles: int,
    gradient_seen: dict[str, bool],
) -> tuple[int, dict[str, Any], list[ProMask], dict[str, Any]]:
    model.train()
    train_slices = data.roles["train"]
    positive_weight = torch.as_tensor(
        data.preprocessing.positive_weight, dtype=torch.float32, device=device
    )
    losses = {"ordinary": [], "gap": []}
    mask_records: list[ProMask] = []
    diagnostics: list[dict[str, Any]] = []
    step_records: list[dict[str, Any]] = []
    gradient_norms: list[float] = []
    for cycle in range(cycles):
        global_cycle = epoch * OPTIMIZATION_CONTRACT["cycles_per_epoch"] + cycle
        for family in ("ordinary", "gap"):
            global_step += 1
            lr = learning_rate_for_step(global_step)
            for parameter_group in optimizer.param_groups:
                parameter_group["lr"] = lr
            optimizer.zero_grad(set_to_none=True)
            order = torch.randperm(
                len(train_slices), generator=data_order_generator
            ).tolist()
            diagnostic_step = (
                (epoch == 0 and cycle == 0 and family == "gap")
                or (
                    (epoch + 1) % 5 == 0
                    and cycle == cycles - 1
                    and family == "gap"
                )
            )
            diagnostic_auxiliary = None
            step_losses: list[torch.Tensor] = []
            ordered_inputs: list[tuple[ProNORMSTSlice, ProMask]] = []
            for slice_offset in order:
                item = train_slices[slice_offset]
                identity = make_mask_identity(
                    protocol=protocol,
                    fold=fold,
                    role="train",
                    slice_id=item.slice_id,
                    family=family,
                    mask_index=global_cycle,
                )
                mask = generate_mask(geometries[item.slice_id], identity)
                mask_records.append(mask)
                ordered_inputs.append((item, mask))

            train_batch_size = OPTIMIZATION_CONTRACT["train_slice_batch_size"]
            input_batches: list[list[tuple[ProNORMSTSlice, ProMask]]] = []
            batch_start = 0
            if diagnostic_step:
                # Preserve the historical single-slice diagnostic witness and
                # its per-round retained gradients while batching the rest.
                input_batches.append(ordered_inputs[:1])
                batch_start = 1
            for offset in range(batch_start, len(ordered_inputs), train_batch_size):
                input_batches.append(
                    ordered_inputs[offset : offset + train_batch_size]
                )

            slice_batches = []
            for batch_offset, input_batch in enumerate(input_batches):
                items = [item for item, _ in input_batch]
                masks = [mask for _, mask in input_batch]
                slice_batches.append([item.slice_id for item in items])
                packed = build_padded_model_batch(items, masks, device)
                want_auxiliary = diagnostic_step and batch_offset == 0
                with torch.amp.autocast(device_type=device.type, enabled=use_amp):
                    output = model(
                        packed.visible_z,
                        packed.visible_index,
                        packed.query_index,
                        packed.geometry,
                        return_auxiliary=want_auxiliary,
                        return_diagnostics=want_auxiliary,
                    )
                prediction_z, auxiliary = output if isinstance(output, tuple) else (output, None)
                item_losses = weighted_gene_smooth_l1_per_item(
                    prediction_z,
                    packed.target_z,
                    positive_weight,
                    packed.query_valid,
                )
                if want_auxiliary and isinstance(auxiliary, dict):
                    local_diagnostics = auxiliary.get("local_diagnostics", {})
                    for state in local_diagnostics.get("round_states", []):
                        if isinstance(state, torch.Tensor) and state.requires_grad:
                            state.retain_grad()
                scaler.scale(item_losses.sum() / len(train_slices)).backward()
                step_losses.extend(item_losses.detach().unbind())
                if want_auxiliary:
                    diagnostic_auxiliary = auxiliary
            scaler.unscale_(optimizer)
            gradient_items = [
                (name, parameter.grad)
                for name, parameter in model.named_parameters()
                if parameter.requires_grad and parameter.grad is not None
            ]
            if not gradient_items:
                raise RuntimeError("optimizer step produced no parameter gradients")
            try:
                gradient_norm = torch.nn.utils.clip_grad_norm_(
                    [
                        parameter
                        for parameter in model.parameters()
                        if parameter.requires_grad
                    ],
                    max_norm=1.0,
                    error_if_nonfinite=True,
                )
            except RuntimeError as error:
                nonfinite_parameters = [
                    name
                    for name, gradient in gradient_items
                    if not bool(torch.isfinite(gradient).all())
                ]
                if nonfinite_parameters:
                    raise FloatingPointError(
                        "non-finite gradient in parameters: "
                        + ", ".join(sorted(nonfinite_parameters))
                    ) from error
                raise
            unseen_gradient_items = [
                (name, gradient)
                for name, gradient in gradient_items
                if not gradient_seen[name]
            ]
            nonzero_values = (
                torch.stack(
                    [(gradient != 0).any() for _, gradient in unseen_gradient_items]
                ).detach().cpu().tolist()
                if unseen_gradient_items
                else []
            )
            step_statistics = torch.cat(
                [
                    torch.stack(step_losses).float(),
                    gradient_norm.detach().reshape(1).float(),
                ]
            ).cpu().tolist()
            gradient_norm_value = float(step_statistics[-1])
            gradient_norms.append(gradient_norm_value)
            if not math.isfinite(gradient_norm_value):
                raise FloatingPointError("non-finite gradient norm")
            for (name, _), nonzero in zip(
                unseen_gradient_items,
                nonzero_values,
                strict=True,
            ):
                if nonzero:
                    gradient_seen[name] = True
            scaler.step(optimizer)
            scaler.update()
            step_loss = float(np.mean(step_statistics[:-1]))
            losses[family].append(step_loss)
            step_records.append(
                {
                    "epoch": epoch + 1,
                    "cycle": cycle + 1,
                    "family": family,
                    "global_step": global_step,
                    "loss": step_loss,
                    "learning_rate": lr,
                    "gradient_norm_preclip": gradient_norm_value,
                    "gradient_clip_max_norm": 1.0,
                    "slice_order": [train_slices[index].slice_id for index in order],
                    "slice_batches": slice_batches,
                }
            )
            if diagnostic_auxiliary is not None:
                diagnostics.append(
                    {
                        "epoch": epoch + 1,
                        "cycle": cycle + 1,
                        "family": family,
                        "global_step": global_step,
                        **diagnostic_summary(diagnostic_auxiliary, gradient_norm_value),
                    }
                )
    return (
        global_step,
        {
            "ordinary": float(np.mean(losses["ordinary"])),
            "gap": float(np.mean(losses["gap"])),
            "combined": float(0.5 * (np.mean(losses["ordinary"]) + np.mean(losses["gap"]))),
        },
        mask_records,
        {
            **gradient_seen,
            "__diagnostics__": diagnostics,
            "__step_records__": step_records,
            "__gradient_norm_mean__": float(np.mean(gradient_norms)),
            "__gradient_norm_max__": float(np.max(gradient_norms)),
        },
    )


def _pilot_gate(validation: dict[str, Any]) -> dict[str, Any]:
    family_status = {}
    passed = True
    for family in ("ordinary", "gap"):
        summary = validation["families"][family]["summary"]
        model_smooth = summary["model"]["smooth_l1"]
        idw_smooth = summary["idw"]["smooth_l1"]
        variance = summary["model"]["variance_ratio_median"]
        family_pass = (
            isinstance(model_smooth, (int, float))
            and isinstance(idw_smooth, (int, float))
            and isinstance(variance, (int, float))
            and model_smooth <= 1.2 * idw_smooth
            and 1e-3 <= variance <= 10.0
        )
        family_status[family] = {
            "passed": family_pass,
            "model_smooth_l1": model_smooth,
            "idw_smooth_l1": idw_smooth,
            "variance_ratio_median": variance,
        }
        passed = passed and family_pass
    return {"passed": passed, "families": family_status}


def _final_loss_bptt_gate(
    history: list[dict[str, Any]], variant: str
) -> dict[str, Any]:
    records = []
    for epoch in history:
        for diagnostic in epoch.get("diagnostics", []):
            norms = diagnostic.get("final_loss_round_state_gradient_norm")
            if isinstance(norms, list):
                records.append(
                    {
                        "epoch": epoch.get("epoch"),
                        "global_step": diagnostic.get("global_step"),
                        "round_gradient_norm": norms,
                    }
                )
    if variant == "global-only":
        return {
            "schema": "pro-normst-final-loss-bptt-v1",
            "applicable": False,
            "passed": True,
            "records": records,
        }
    required_rounds = 1 if variant == "one-shot" else 4
    passed_record = False
    for record in records:
        norms = record["round_gradient_norm"]
        if len(norms) != required_rounds:
            continue
        numeric = [
            float(value)
            for value in norms
            if isinstance(value, (int, float)) and math.isfinite(value)
        ]
        if len(numeric) == required_rounds and all(value > 0 for value in numeric):
            passed_record = True
            break
    return {
        "schema": "pro-normst-final-loss-bptt-v1",
        "applicable": True,
        "required_rounds": required_rounds,
        "passed": passed_record,
        "records": records,
    }


def _prediction_tree_sha256(root: Path) -> str:
    files = sorted(root.rglob("*.npz"))
    if not files:
        raise ValueError(f"test prediction tree is empty: {root}")
    digest = hashlib.sha256()
    for path in files:
        relative = str(path.relative_to(root)).replace("\\", "/")
        digest.update(relative.encode("utf-8"))
        digest.update(file_sha256(path).encode("ascii"))
    return digest.hexdigest()


def _load_committed_test(
    artifact_dir: Path,
    *,
    checkpoint_path: Path,
    checkpoint_lock_path: Path | None,
    contract_hash: str,
    test_data_identity: dict[str, str],
    primary_round: int,
) -> dict[str, Any] | None:
    if not artifact_dir.exists():
        return None
    if not artifact_dir.is_dir():
        raise ValueError(f"test artifact path is not a directory: {artifact_dir}")
    metrics_path = artifact_dir / "test_metrics.json"
    marker_path = artifact_dir / "test_complete.json"
    if not metrics_path.is_file() or not marker_path.is_file():
        raise ValueError("committed test artifact directory is incomplete")
    results = json.loads(metrics_path.read_text(encoding="utf-8"))
    marker = json.loads(marker_path.read_text(encoding="utf-8"))
    expected_checkpoint_hash = file_sha256(checkpoint_path)
    expected_checkpoint_lock_hash = (
        file_sha256(checkpoint_lock_path) if checkpoint_lock_path is not None else None
    )
    expected_rounds = sorted(key for key in results if key.startswith("round"))
    valid = (
        marker.get("status") == "complete"
        and marker.get("checkpoint_sha256") == expected_checkpoint_hash
        and marker.get("run_checkpoint_lock_sha256")
        == expected_checkpoint_lock_hash
        and marker.get("contract_hash") == contract_hash
        and marker.get("test_metrics_sha256") == file_sha256(metrics_path)
        and marker.get("test_expression_x_sha256") == test_data_identity
        and marker.get("primary_round") == primary_round
        and marker.get("round_evidence") == expected_rounds
        and marker.get("prediction_tree_sha256")
        == _prediction_tree_sha256(artifact_dir / "predictions")
        and results.get("_meta", {}).get("contract_hash") == contract_hash
        and results.get("_meta", {}).get("test_expression_x_sha256")
        == test_data_identity
    )
    if not valid:
        raise ValueError("committed test artifacts do not match the locked evaluation")
    return results


def _run_test_once(
    *,
    model: ProNORMST,
    data: ProNORMSTData,
    banks: dict[str, dict[str, dict[str, tuple[ProMask, ...]]]],
    output_dir: Path,
    device: torch.device,
    use_amp: bool,
    checkpoint_path: Path,
    checkpoint_lock_path: Path | None = None,
    protocol: str,
    contract_hash: str,
    control_cache: EvaluationControlCache | None = None,
    persistent_idw_cache: PersistentIDWCache | None = None,
) -> dict[str, Any]:
    if protocol == "pair_grouped_lodo":
        if checkpoint_lock_path is None or not checkpoint_lock_path.is_file():
            raise ValueError("formal test requires a pre-test run checkpoint lock")
        _validate_run_checkpoint_lock(
            checkpoint_lock_path, checkpoint_path, contract_hash
        )
    elif checkpoint_lock_path is not None:
        raise ValueError("pilot test must not consume a run checkpoint lock")
    test_data_identity = test_expression_identity(data)
    primary_round = 4 if model.variant != "one-shot" else 1
    artifact_dir = output_dir / TEST_ARTIFACTS_DIRECTORY
    committed = _load_committed_test(
        artifact_dir,
        checkpoint_path=checkpoint_path,
        checkpoint_lock_path=checkpoint_lock_path,
        contract_hash=contract_hash,
        test_data_identity=test_data_identity,
        primary_round=primary_round,
    )
    if committed is not None:
        return committed

    staging = output_dir / f".{TEST_ARTIFACTS_DIRECTORY}.tmp"
    if staging.exists():
        if not staging.is_dir():
            raise ValueError(f"test staging path is not a directory: {staging}")
        try:
            staged = _load_committed_test(
                staging,
                checkpoint_path=checkpoint_path,
                checkpoint_lock_path=checkpoint_lock_path,
                contract_hash=contract_hash,
                test_data_identity=test_data_identity,
                primary_round=primary_round,
            )
        except (OSError, ValueError):
            shutil.rmtree(staging)
        else:
            os.replace(staging, artifact_dir)
            return staged
    _preload_resident_roles(data, device, ("test",))
    staging.mkdir(parents=False)
    primary = _evaluate_role(
        model,
        data,
        "test",
        banks,
        device,
        use_amp=use_amp,
        output_dir=staging,
        prediction_label=f"test_round{primary_round}",
        round_limit=primary_round,
        control_cache=control_cache,
        persistent_idw_cache=persistent_idw_cache,
    )
    results: dict[str, Any] = {
        "_meta": {
            "schema": "pro-normst-test-metrics-v1",
            "contract_hash": contract_hash,
            "test_expression_x_sha256": test_data_identity,
        },
        f"round{primary_round}": primary,
    }
    if protocol == "pair_grouped_lodo" and model.variant == "full":
        for round_limit in (1, 2):
            results[f"round{round_limit}"] = _evaluate_role(
                model,
                data,
                "test",
                banks,
                device,
                use_amp=use_amp,
                output_dir=staging,
                prediction_label=f"test_round{round_limit}",
                round_limit=round_limit,
                control_cache=control_cache,
                persistent_idw_cache=persistent_idw_cache,
            )
    metrics_path = staging / "test_metrics.json"
    _write_json(metrics_path, results, allow_replace=False)
    marker_payload = {
        "status": "complete",
        "checkpoint": str(checkpoint_path.resolve()),
        "checkpoint_sha256": file_sha256(checkpoint_path),
        "run_checkpoint_lock_sha256": (
            file_sha256(checkpoint_lock_path)
            if checkpoint_lock_path is not None
            else None
        ),
        "contract_hash": contract_hash,
        "test_metrics_sha256": file_sha256(metrics_path),
        "test_expression_x_sha256": test_data_identity,
        "primary_round": primary_round,
        "round_evidence": sorted(key for key in results if key.startswith("round")),
        "prediction_tree_sha256": _prediction_tree_sha256(staging / "predictions"),
    }
    _write_json(staging / "test_complete.json", marker_payload, allow_replace=False)
    os.replace(staging, artifact_dir)
    return results


def main(argv: list[str] | None = None) -> int:
    main_started = time.perf_counter()
    args = parse_args(argv)
    device = _device_from_argument(args.device)
    data = prepare_pro_normst_data(args.manifest, args.panel, count_file=args.count_file)
    protocol, fold = _split_identity(data)
    _validate_args(args, protocol)
    seed_initialization(args.seed)
    model = ProNORMST(
        torch.as_tensor(data.preprocessing.gene_mean_z), variant=args.variant
    ).to(device)
    optimizer, parameter_groups = optimizer_for_model(model)
    use_amp = device.type == "cuda"
    scaler = torch.amp.GradScaler(device.type, enabled=use_amp)
    data_order_generator = torch.Generator(device="cpu")
    data_order_generator.manual_seed(OPTIMIZATION_CONTRACT["data_order_seed"])
    geometries = _build_geometries(data)
    banks = _build_fixed_banks(data, geometries, protocol, fold)
    evaluation_control_cache: EvaluationControlCache = {}
    persistent_idw_cache = (
        PersistentIDWCache(args.idw_cache_dir)
        if args.idw_cache_dir is not None
        else None
    )
    contract_manifest = _contract_manifest(
        args, data, model, protocol, fold, geometries, banks
    )
    contract_hash = _numerical_contract_hash(contract_manifest)
    if protocol == "pair_grouped_lodo":
        _validate_candidate_lock(args.candidate_lock, contract_manifest)
    resident_cache = (
        {"roles": [], "slice_ids": [], "bytes": 0, "seconds": 0.0}
        if args.predict_only
        else _preload_resident_roles(data, device, ("train", "val"))
    )
    output_dir = args.output_dir.resolve()

    fresh = not args.resume and not args.predict_only
    if fresh:
        if output_dir.exists():
            raise FileExistsError(f"run directory already exists: {output_dir}")
        output_dir.mkdir(parents=True)
        _save_run_artifacts(
            output_dir,
            args,
            data,
            model,
            parameter_groups,
            protocol,
            fold,
            contract_manifest,
            contract_hash,
            banks,
        )
    else:
        if not output_dir.is_dir():
            raise FileNotFoundError(output_dir)
        _validate_existing_run(
            output_dir, args, data, contract_manifest, contract_hash
        )
    print(
        json.dumps(
            {
                "event": "runtime_setup",
                "seconds": time.perf_counter() - main_started,
                "resident_tensor_cache": resident_cache,
                "persistent_idw_cache": _persistent_idw_cache_status(
                    persistent_idw_cache
                ),
            },
            sort_keys=True,
        ),
        flush=True,
    )

    if args.predict_only:
        locked_best = (output_dir / "best.pt").resolve()
        if not locked_best.is_file():
            raise FileNotFoundError(locked_best)
        checkpoint_path = (args.checkpoint or locked_best).resolve()
        if file_sha256(checkpoint_path) != file_sha256(locked_best):
            raise ValueError("predict-only checkpoint must be byte-identical to locked best.pt")
        checkpoint = _load_checkpoint(checkpoint_path, model, contract_hash, device)
        checkpoint_lock_path = None
        if protocol == "pair_grouped_random_split":
            _write_candidate_lock(output_dir, contract_manifest)
        else:
            checkpoint_lock_path = _write_run_checkpoint_lock(
                output_dir,
                checkpoint_path,
                checkpoint,
                contract_hash,
            )
        evaluation_control_cache.clear()
        test_control_cache = (
            evaluation_control_cache
            if protocol == "pair_grouped_lodo" and model.variant == "full"
            else None
        )
        test_started = time.perf_counter()
        _run_test_once(
            model=model,
            data=data,
            banks=banks,
            output_dir=output_dir,
            device=device,
            use_amp=use_amp,
            checkpoint_path=checkpoint_path,
            checkpoint_lock_path=checkpoint_lock_path,
            protocol=protocol,
            contract_hash=contract_hash,
            control_cache=test_control_cache,
            persistent_idw_cache=persistent_idw_cache,
        )
        print(
            json.dumps(
                {
                    "event": "runtime_test",
                    "seconds": time.perf_counter() - test_started,
                    "cached_fixed_mask_controls": len(evaluation_control_cache),
                    "persistent_idw_cache": _persistent_idw_cache_status(
                        persistent_idw_cache
                    ),
                },
                sort_keys=True,
            ),
            flush=True,
        )
        _write_json(
            output_dir / "run_status.json",
            {
                "status": "complete",
                "test_run": True,
                "best_epoch": int(checkpoint["best_epoch"]),
                "best_validation": float(checkpoint["best_value"]),
                "checkpoint_sha256": file_sha256(checkpoint_path),
            },
            allow_replace=False,
        )
        return 0

    start_epoch = 0
    global_step = 0
    best_value = math.inf
    best_epoch = -1
    bad_epochs = 0
    history: list[dict[str, Any]] = []
    gradient_cache: dict[str, float] = {}
    gradient_seen = {name: False for name in model.trainable_parameter_names()}
    if args.resume:
        checkpoint = _load_checkpoint(
            output_dir / "last.pt",
            model,
            contract_hash,
            device,
            optimizer=optimizer,
            scaler=scaler,
            data_order_generator=data_order_generator,
        )
        start_epoch = int(checkpoint["epoch"])
        global_step = int(checkpoint["global_step"])
        best_value = float(checkpoint["best_value"])
        best_epoch = int(checkpoint["best_epoch"])
        bad_epochs = int(checkpoint["bad_epochs"])
        history = checkpoint["history"]
        gradient_cache = checkpoint.get("gradient_cache", {})
        gradient_seen.update(checkpoint.get("gradient_seen", {}))

    cycles = OPTIMIZATION_CONTRACT["cycles_per_epoch"]
    for epoch in range(start_epoch, args.epochs):
        if bad_epochs >= OPTIMIZATION_CONTRACT["early_stopping_patience"]:
            break
        if device.type == "cuda":
            torch.cuda.reset_peak_memory_stats(device)
        epoch_started = time.perf_counter()
        train_started = time.perf_counter()
        global_step, train_loss, mask_records, gradient_state = _train_one_epoch(
            model=model,
            data=data,
            geometries=geometries,
            optimizer=optimizer,
            scaler=scaler,
            data_order_generator=data_order_generator,
            device=device,
            use_amp=use_amp,
            protocol=protocol,
            fold=fold,
            epoch=epoch,
            global_step=global_step,
            cycles=cycles,
            gradient_seen=gradient_seen,
        )
        train_seconds = time.perf_counter() - train_started
        diagnostics = gradient_state.pop("__diagnostics__")
        step_records = gradient_state.pop("__step_records__")
        gradient_norm_mean = float(gradient_state.pop("__gradient_norm_mean__"))
        gradient_norm_max = float(gradient_state.pop("__gradient_norm_max__"))
        gradient_seen.update(gradient_state)
        validation_started = time.perf_counter()
        validation = _evaluate_role(
            model,
            data,
            "val",
            banks,
            device,
            use_amp=use_amp,
            detail="summary",
            control_cache=evaluation_control_cache,
            persistent_idw_cache=persistent_idw_cache,
        )
        validation_seconds = time.perf_counter() - validation_started
        criterion = float(validation["criterion_weighted_z_smooth_l1"])
        if not math.isfinite(criterion):
            raise FloatingPointError("validation criterion is non-finite")
        gradient_cache[str(epoch + 1)] = gradient_norm_mean
        record = {
            "epoch": epoch + 1,
            "global_step": global_step,
            "train_loss": train_loss,
            "validation": validation,
            "learning_rate": optimizer.param_groups[0]["lr"],
            "gradient_norm_preclip_mean": gradient_norm_mean,
            "gradient_norm_preclip_max": gradient_norm_max,
            "diagnostics": diagnostics,
        }
        history.append(record)
        mask_artifacts = _save_training_mask_epoch(
            output_dir,
            epoch + 1,
            mask_records,
        )
        step_history_path = output_dir / "step_history" / f"epoch_{epoch + 1:03d}.json"
        _write_json(
            step_history_path,
            {
                "schema": "pro-normst-step-history-v1",
                "epoch": epoch + 1,
                "steps": step_records,
            },
            allow_replace=False,
        )
        record["training_mask_artifacts"] = mask_artifacts
        record["step_history_sha256"] = file_sha256(step_history_path)
        improved = criterion < best_value - OPTIMIZATION_CONTRACT["early_stopping_min_delta"]
        if improved:
            best_value = criterion
            best_epoch = epoch + 1
            bad_epochs = 0
        else:
            bad_epochs += 1
        payload = _checkpoint_payload(
            model=model,
            optimizer=optimizer,
            scaler=scaler,
            data_order_generator=data_order_generator,
            contract_hash=contract_hash,
            epoch=epoch + 1,
            global_step=global_step,
            best_value=best_value,
            best_epoch=best_epoch,
            bad_epochs=bad_epochs,
            history=history,
            gradient_cache=gradient_cache,
            gradient_seen=gradient_seen,
        )
        _save_torch(output_dir / "last.pt", payload)
        if improved:
            _save_torch(output_dir / "best.pt", payload)
        _write_json(output_dir / "history.json", history)
        print(
            json.dumps(
                {
                    "event": "runtime_epoch",
                    "epoch": epoch + 1,
                    "train_seconds": train_seconds,
                    "validation_seconds": validation_seconds,
                    "total_seconds": time.perf_counter() - epoch_started,
                    "cached_fixed_mask_controls": len(evaluation_control_cache),
                    "cuda_peak_memory": _cuda_peak_memory(device),
                    "persistent_idw_cache": _persistent_idw_cache_status(
                        persistent_idw_cache
                    ),
                },
                sort_keys=True,
            ),
            flush=True,
        )
        if bad_epochs >= OPTIMIZATION_CONTRACT["early_stopping_patience"]:
            break

    missing_gradient = sorted(name for name, seen in gradient_seen.items() if not seen)
    gradient_gate = {"passed": not missing_gradient, "missing_nonzero_gradient": missing_gradient}
    _write_json(output_dir / "gradient_gate.json", gradient_gate, allow_replace=False)
    if missing_gradient:
        raise RuntimeError(f"trainable parameters never received a nonzero gradient: {missing_gradient}")
    bptt_gate = _final_loss_bptt_gate(history, model.variant)
    _write_json(
        output_dir / "final_loss_bptt_gate.json",
        bptt_gate,
        allow_replace=False,
    )
    if not bptt_gate["passed"]:
        raise RuntimeError("final gene loss did not verify full-BPTT through local rounds")
    if args.smoke:
        smoke_verification = _verify_smoke_checkpoint(
            model=model,
            optimizer=optimizer,
            scaler=scaler,
            data_order_generator=data_order_generator,
            data=data,
            banks=banks,
            output_dir=output_dir,
            device=device,
            use_amp=use_amp,
            contract_hash=contract_hash,
        )
        _write_json(
            output_dir / "run_status.json",
            {
                "status": "smoke-complete",
                "evidence": "engineering-only",
                "test_run": False,
                "smoke_verification_passed": smoke_verification["passed"],
                "best_epoch": best_epoch,
                "best_validation": best_value,
            },
            allow_replace=False,
        )
        return 0

    best_path = output_dir / "best.pt"
    best_checkpoint = _load_checkpoint(best_path, model, contract_hash, device)
    best_validation = history[best_epoch - 1]["validation"]
    first_val = data.roles["val"][0]
    first_mask = banks["val"][first_val.slice_id]["gap"][0]
    diagnostic_record = evaluate_mask(
        model,
        first_val,
        first_mask,
        data.preprocessing.gene_scale,
        data.preprocessing.positive_weight,
        data.preprocessing.detection_rate,
        device,
        use_amp=use_amp,
        return_auxiliary=True,
        control_cache=evaluation_control_cache,
        persistent_idw_cache=persistent_idw_cache,
    )
    final_diagnostics = diagnostic_summary(
        diagnostic_record["auxiliary"],
        best_checkpoint.get("gradient_cache", {}).get(str(best_epoch)),
    )
    _write_json(output_dir / "best_diagnostics.json", final_diagnostics, allow_replace=False)

    if protocol == "pair_grouped_random_split":
        gate = _pilot_gate(best_validation)
        _write_json(output_dir / "pilot_gate.json", gate, allow_replace=False)
        if not gate["passed"]:
            _write_json(
                output_dir / "run_status.json",
                {
                    "status": "pilot-health-gate-failed",
                    "test_run": False,
                    "best_epoch": best_epoch,
                    "best_validation": best_value,
                },
                allow_replace=False,
            )
            return 0
        _write_candidate_lock(output_dir, contract_manifest)

    checkpoint_lock_path = None
    if protocol == "pair_grouped_lodo":
        checkpoint_lock_path = _write_run_checkpoint_lock(
            output_dir,
            best_path,
            best_checkpoint,
            contract_hash,
        )
    evaluation_control_cache.clear()
    test_control_cache = (
        evaluation_control_cache
        if protocol == "pair_grouped_lodo" and model.variant == "full"
        else None
    )
    test_started = time.perf_counter()
    _run_test_once(
        model=model,
        data=data,
        banks=banks,
        output_dir=output_dir,
        device=device,
        use_amp=use_amp,
        checkpoint_path=best_path,
        checkpoint_lock_path=checkpoint_lock_path,
        protocol=protocol,
        contract_hash=contract_hash,
        control_cache=test_control_cache,
        persistent_idw_cache=persistent_idw_cache,
    )
    print(
        json.dumps(
            {
                "event": "runtime_test",
                "seconds": time.perf_counter() - test_started,
                "cached_fixed_mask_controls": len(evaluation_control_cache),
                "persistent_idw_cache": _persistent_idw_cache_status(
                    persistent_idw_cache
                ),
            },
            sort_keys=True,
        ),
        flush=True,
    )
    _write_json(
        output_dir / "run_status.json",
        {
            "status": "complete",
            "test_run": True,
            "best_epoch": best_epoch,
            "best_validation": best_value,
            "checkpoint_sha256": file_sha256(best_path),
        },
        allow_replace=False,
    )
    return 0


__all__ = ["main", "parse_args"]
